# Generated by Django 4.0.1 on 2022-01-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('releasing_date', models.DateField(auto_now=True)),
                ('description', models.CharField(max_length=1000)),
                ('movie_timings', models.DateTimeField(auto_now=True)),
                ('make_payment', models.BooleanField()),
            ],
        ),
    ]
